annotations:
  category: DeveloperTools
apiVersion: v2
appVersion: 1.9.20
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://marketplace.azurecr.io/helm/v1/repo
    version: 10.x.x
  - name: common
    repository: https://marketplace.azurecr.io/helm/v1/repo
    tags:
      - bitnami-common
    version: 1.x.x
# The TestLink chart is deprecated and no longer maintained.
deprecated: true
description: DEPRECATED TestLink is test management software that facilitates software quality assurance. It suppors test cases, test suites, test plans, test projects and user management, and stats reporting.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/testlink
icon: https://bitnami.com/assets/stacks/testlink/img/testlink-stack-220x234.png
keywords:
  - testlink
  - testing
  - http
  - php
maintainers: []
name: testlink
sources:
  - https://github.com/bitnami/bitnami-docker-testlink
  - https://www.testlink.org/
version: 10.0.16