annotations:
  category: CMS
apiVersion: v2
appVersion: 4.0.5
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://marketplace.azurecr.io/helm/v1/repo
    version: 9.x.x
  - name: common
    repository: https://marketplace.azurecr.io/helm/v1/repo
    version: 1.x.x
description: PHP content management system (CMS) for publishing web content
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/joomla
icon: https://bitnami.com/assets/stacks/joomla/img/joomla-stack-220x234.png
keywords:
  - joomla
  - cms
  - blog
  - http
  - php
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: joomla
sources:
  - https://github.com/bitnami/bitnami-docker-joomla
  - https://www.joomla.org/
version: 11.0.0